const menudata = [
    {
        id: 1,
        img: "/mexican.jpg",
        title: "Mexican Burrito Bowl",
        cal: "291 cal | Calorie",
        disc: "Here is our all time favourite signature burrito bowl. Paneer steaks, infused with hot and tangy habanero-...",
        disprice: "₹98",
        price: "₹299",
        discout: "(67% OFF)",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    },
    {
        id: 2,
        img: "/ultimate.jpg",
        title: "Ultimate Burrito Bowl",
        cal: "370 cal | Calorie",
        disc: "This bowl contains mexican tomato rice loaded with toppings to give you a full-satisfying meal. Fresh paneer-...",
        disprice: "₹98",
        price: "₹299",
        discout: "(67% OFF)",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    },
    {
        id: 3,
        img: "/chipotle.jpg",
        title: "Chipotle Paneer Burrito Bowl",
        cal: "Continental",
        disc: "A perfect blend of bold and fresh! Smoky Peri Peri paneer, zesty cilantro rice, and hearty beans come together with...",
        disprice: "₹118",
        price: "₹399",
        discout: "(65% OFF)",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    },
    {
        id: 4,
        img: "/honey.jpg",
        title: "Honey Mustard Cremosa Burrito",
        cal: "Continental",
        disc: "Cilantro rice topped with sweet and tangy honey mustard sauce, grilled paneer, mixed veggie salad, sour cream, and more...",
        disprice: "₹118",
        price: "₹299",
        discout: "(61% OFF)",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    },
    {
        id: 5,
        img: "/cheesey.jpg",
        title: "Cheesey Double XL Burrito",
        cal: "Continental",
        disc: "Enjoy a hearty base of vibrant cilantro lime rice, generously topped with a double serving of our delicious grilled paneer, cheese sauce, and veggies...",
        disprice: "₹168",
        price: "₹399",
        discout: "(58% OFF)",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    },
    {
        id: 6,
        img: "/cremosa.jpg",
        title: "Cremosa Paneer Burrito",
        cal: "Continental",
        disc: "A hearty bowl of cilantro rice topped with a creamy mix of béchamel and tomato sauce, topped with perfectly grilled paneer and fresh veggies...",
        disprice: "₹118",
        price: "₹299",
        discout: "(61% OFF)",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    },
    {
        id: 7,
        img: "/chargrilled.jpg",
        title: "Chargrilled Moroccan Cottage Burrito",
        cal: "Continental",
        disc: "Enjoy the refreshing flavors of this Middle Eastern-inspired bowl. Grilled cottage cheese cubes and peppers paired with aromatic spices...",
        disprice: "₹118",
        price: "₹299",
        discout: "(61% OFF)",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    },
    {
        id: 8,
        img: "/boston.jpg",
        title: "Boston Grill Chicken Burrito",
        cal: "Continental",
        disc: "Savor a hearty bowl layered with zesty cilantro rice and tender herb-grilled chicken for a wholesome and satisfying meal...",
        disprice: "₹120",
        price: "₹299",
        discout: "(60% OFF)",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    },
    {
        id: 9,
        img: "/cincinnati.jpg",
        title: "Cincinnati Chili Burrito Bowl",
        cal: "Continental",
        disc: "Zesty cilantro rice sets the base for a burst of flavors, topped with spicy peri peri paneer that delivers a bold taste...",
        disprice: "₹120",
        price: "₹299",
        discout: "(60% OFF)",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    },
    {
        id: 10,
        img: "/philadelphia.jpg",
        title: "Philadelphia Cheesesteak Burrito",
        cal: "Continental",
        disc: "Enjoy a vibrant and satisfying bowl layered with zesty cilantro rice, topped with tender herb-grilled chicken and rich cheese sauce...",
        disprice: "₹120",
        price: "₹299",
        discout: "(60% OFF)",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    },
    {
        id: 11,
        img: "/rio.jpg",
        title: "Rio De Janeiro Burrito Bowl",
        cal: "Continental",
        disc: "Tangy cilantro rice forms the base, topped with tender herb-grilled paneer for a flavorful bite packed with freshness...",
        disprice: "₹120",
        price: "₹299",
        discout: "(60% OFF)",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    },
    {
        id: 12,
        img: "/vienna.jpg",
        title: "Vienna Wiener Schnitzel Burrito",
        cal: "Continental",
        disc: "A vibrant fusion feast starts with zesty cilantro rice, layered with crispy fried sausage bringing a hearty and indulgent flavor...",
        disprice: "₹120",
        price: "₹299",
        discout: "(60% OFF)",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    },
    {
        id: 13,
        img: "/pomodoro.jpg",
        title: "Pomodoro Tuscan Burrito Bowl",
        cal: "Continental",
        disc: "Zesty cilantro rice topped with crispy crumb-fried paneer, savory hi-protein black bean taqueria, and fresh pico de gallo...",
        disprice: "₹120",
        price: "₹299",
        discout: "(60% OFF)",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    },
    {
        id: 14,
        img: "/german.jpg",
        title: "German Crispy Potato Burrito",
        cal: "Continental",
        disc: "Crispy fried potato adds satisfying crunch to a base of zesty cilantro rice. Hearty hi-protein black bean taqueria completes the bowl...",
        disprice: "₹120",   
        price: "₹299",
        discout: "(60% OFF)",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    },
    {
        id: 15,
        img: "/teriyaki.jpg",
        title: "Teriyaki Chicken Rice Bowl",
        cal: "Asian",
        disc: "With our Teriyaki Rice Bowl is an all time favourite meal with our guests. Diced, grilled chicken tossed with veggies in rich teriyaki sauce...",
        disprice: "₹299",
        price: "",
        discout: "",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    },
    {
        id: 16,
        img: "/sunny.jpg",
        title: "Sunny Side Egg Fried Rice",
        cal: "Asian",
        disc: "Fluffy rice tossed with carrots, beans, and soft scrambled eggs for that classic wok flavor, topped with a perfectly fried egg...",
        disprice: "₹249",
        price: "",
        discout: "",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    },
    {
        id: 17,
        img: "/friedegg.jpg",
        title: "Fried Egg Teriyaki Noodles",
        cal: "Asian",
        disc: "Wok-tossed noodles loaded with scrambled egg, peppers, onions, cabbage, and carrots — all glazed in a rich teriyaki sauce...",
        disprice: "₹249",
        price: "",
        discout: "",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    },
    {
        id: 18,
        img: "/dan-dan.jpg",
        title: "Dan Dan Chicken Noodles",
        cal: "653 cal | Low Calorie",
        disc: "Minced chicken cooked in a piquant broth of chicken stock, Shaoxing wine, Hoisin sauce, and Sichuan spices for a bold kick...",
        disprice: "₹98",
        price: "₹299",
        discout: "(67% OFF)",
        cart: "Add to Cart",
        custom: "Custom  According To The Customer's"
    }
]
export default menudata